
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: promtail-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - nodes/proxy
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.just-loki.io
  resources:
  - promtails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.just-loki.io
  resources:
  - promtails/finalizers
  verbs:
  - update
- apiGroups:
  - logging.just-loki.io
  resources:
  - promtails/status
  verbs:
  - get
  - patch
  - update
